[package]
name = "rust-goose"
version = "0.1.0"
authors = ["Sébastien Gruchet <sebastien.gruchet@digimind.com>"]
include = ["src/**/*", "test/**/*", "Cargo.toml"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
select = "0.4.3"
